# Markdown Linting Configuration for AI-Enhanced Pull Request Handbook

# Default state for all rules
default: true

# Line length
MD013: false  # Line length - allow longer lines for code examples

# Headers
MD022: true   # Headers should be surrounded by blank lines
MD025: true   # Multiple top-level headers in the same document
MD026: true   # Trailing punctuation in header

# Lists
MD004: false  # Unordered list style - allow mixed styles
MD029: false  # Ordered list item prefix - allow different styles
MD030: false  # Spaces after list markers - allow flexibility

# Code blocks
MD040: true   # Fenced code blocks should have a language specified
MD041: true   # First line in file should be a top level header
MD046: true   # Code block style should be consistent

# Links and images
MD034: true   # Bare URL used
MD045: true   # Images should have alternate text (alt text)

# Emphasis
MD036: true   # Emphasis used instead of a header

# Tables
MD013: false  # Line length - allow longer lines in tables
MD047: true   # Files should end with a single newline character

# Custom rules for the handbook
MD024: false  # Multiple headers with the same content - allow for template sections
MD033: false  # Inline HTML - allow for specific formatting needs
MD036: false  # Emphasis used instead of a header - allow for template formatting

# Allow HTML for specific use cases
MD033: false  # Inline HTML - allow for badges, buttons, etc.

# Allow emphasis for template formatting
MD036: false  # Emphasis used instead of a header - needed for template sections

# Allow multiple headers with same content for templates
MD024: false  # Multiple headers with the same content - needed for template reuse

