name: PR Rules Check

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate-pr-template:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Check PR body against Core Rules
        uses: actions/github-script@v7
        with:
          script: |
            const prBody = context.payload.pull_request.body || "";
            const requiredSections = [
              "### Outcome (Core)",
              "### Risk & Rollback (Core)",
              "### AI Assistance (Core)",
              "Unit tests (Core)",
              "Integration/Contract tests (Core)",
              "Changed-lines coverage (Core)",
              "Secrets scan (Core)",
              "SAST (Core)",
              "SCA/License (Core)",
              "Backward/forward compatibility (Core)",
              "New metrics/traces/logs (Core)",
              "Provenance/SBOM (Core)",
              "### Approvals (Core)"
            ];
            let missing = requiredSections.filter(s => !prBody.includes(s));
            if (missing.length) {
              core.setFailed(`Missing sections: ${missing.join(", ")}`);
            }

  validate-markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Markdown Lint
        uses: DavidAnson/markdownlint-action@v2
        with:
          files: 'docs/ templates/ examples/'
          config: '.markdownlint.yaml'
          
      - name: Check for broken links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
          folder-path: 'docs/ templates/ examples/'

  validate-templates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Validate PR template
        run: |
          if [ -f "templates/pull-request-template.md" ]; then
            echo "✅ PR template exists"
            # Check for required sections in template
            grep -q "### Outcome (Core)" templates/pull-request-template.md || (echo "❌ Missing Outcome section" && exit 1)
            grep -q "### Risk & Rollback (Core)" templates/pull-request-template.md || (echo "❌ Missing Risk & Rollback section" && exit 1)
            grep -q "### AI Assistance (Core)" templates/pull-request-template.md || (echo "❌ Missing AI Assistance section" && exit 1)
            echo "✅ PR template validation passed"
          else
            echo "❌ PR template missing"
            exit 1
          fi
          
      - name: Validate release manifest template
        run: |
          if [ -f "templates/release-manifest-template.md" ]; then
            echo "✅ Release manifest template exists"
            grep -q "## Release Overview" templates/release-manifest-template.md || (echo "❌ Missing Release Overview section" && exit 1)
            grep -q "## Scope of Included Work" templates/release-manifest-template.md || (echo "❌ Missing Scope section" && exit 1)
            echo "✅ Release manifest template validation passed"
          else
            echo "❌ Release manifest template missing"
            exit 1
          fi

  check-file-structure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Validate repository structure
        run: |
          echo "Checking repository structure..."
          
          # Check required directories
          [ -d "docs" ] || (echo "❌ docs/ directory missing" && exit 1)
          [ -d "templates" ] || (echo "❌ templates/ directory missing" && exit 1)
          [ -d "examples" ] || (echo "❌ examples/ directory missing" && exit 1)
          [ -d ".github/workflows" ] || (echo "❌ .github/workflows/ directory missing" && exit 1)
          
          # Check required files
          [ -f "README.md" ] || (echo "❌ README.md missing" && exit 1)
          [ -f "CONTRIBUTING.md" ] || (echo "❌ CONTRIBUTING.md missing" && exit 1)
          [ -f "LICENSE" ] || (echo "❌ LICENSE missing" && exit 1)
          
          echo "✅ Repository structure validation passed"

